services:
  api:
    image: fspelling/vertical-slice-api:latest
    ports:
      - "5193:5193"
    networks:
      - observability
    volumes:
      - "./logs/api:/log"
  
  loki:
    image: grafana/loki:2.0.0
    ports:
      - "3100:3100"
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    networks:
      - observability

  promtail:
    image: grafana/promtail:2.0.0
    ports:
      - 9080:9080
    command:
      - -config.file=/etc/promtail/config.yaml
    volumes:
      - "./promtail/config.yaml:/etc/promtail/config.yaml"
      - "./logs/api:/logs/api"
      - "./tmp:/tmp"
    networks:
      - observability

  prometheus:
    image: prom/prometheus:v2.24.1
    ports:
      - "9090:9090"
    depends_on:
      - api
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yaml:/etc/prometheus/alert.rules.yaml
    networks:
      - observability

  alertmanager:
    image: prom/alertmanager:v0.21.0
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yaml:/prometheus/alertmanager.yml
    command:
      - '--config.file=/prometheus/alertmanager.yml'
    networks:
      - observability

networks:
  observability:
    driver: bridge
