global:

route:
  receiver: Default
  group_by: ['alertname']
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m

  routes:
    - receiver: AlertaWebApi
      match:
        team: webapi

receivers:
  - name: Default
    webhook_configs:
      - url: https://webhook.site/679b437d-51a7-4449-b0f4-2815ac3d7634
  - name: AlertaWebApi
    webhook_configs:
      - url: https://webhook.site/679b437d-51a7-4449-b0f4-2815ac3d7634
