global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - alert.rules.yaml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'api'
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets:
          - 'api:5193'
        labels:
          versao: "1.0"
          
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - 'alertmanager:9093'
